// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyD4OnKdEjeFdZFKhqLHp9Dusn-trLbus0I',
//     appId: '1:203825944545:web:ec87ee78f62dc959d8a4a0',
//     messagingSenderId: '203825944545',
//     projectId: 'iattendy',
//     authDomain: 'iattendy.firebaseapp.com',
//     storageBucket: 'iattendy.firebasestorage.app',
//     measurementId: 'G-2V0WC5JN6T',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAacIXX7vKizXCFrwljc4GZ6W3BOwfl7Mg',
//     appId: '1:203825944545:android:3b6c1bd2b9eb6792d8a4a0',
//     messagingSenderId: '203825944545',
//     projectId: 'iattendy',
//     storageBucket: 'iattendy.firebasestorage.app',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDxiOuVPCXZ7gaePSJ2hWp1x6FGbI-0aA4',
//     appId: '1:203825944545:ios:ca5ff02fa3032300d8a4a0',
//     messagingSenderId: '203825944545',
//     projectId: 'iattendy',
//     storageBucket: 'iattendy.firebasestorage.app',
//     iosBundleId: 'com.example.googleMlFaceDetection',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDxiOuVPCXZ7gaePSJ2hWp1x6FGbI-0aA4',
//     appId: '1:203825944545:ios:177635d7d57ffbafd8a4a0',
//     messagingSenderId: '203825944545',
//     projectId: 'iattendy',
//     storageBucket: 'iattendy.firebasestorage.app',
//     iosBundleId: 'com.example.googleMlFaceDetection',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyD4OnKdEjeFdZFKhqLHp9Dusn-trLbus0I',
//     appId: '1:203825944545:web:3115ddcae43aea2cd8a4a0',
//     messagingSenderId: '203825944545',
//     projectId: 'iattendy',
//     authDomain: 'iattendy.firebaseapp.com',
//     storageBucket: 'iattendy.firebasestorage.app',
//     measurementId: 'G-QVWNQ0WFP1',
//   );
//
// }